### ISSUE TITLE
Improper Periodicity 

### ISSUE THREAD

**Issue by jmaat** [openforcefield/openforcefield#176] opened 2019-02-07 23:56 UTC
Does the current version support a periodicity2, phase2 and k2 for improper terms? If not can this be integrated into the next release? @j-wags 

We are trying to capture this energetic behavior with the improper term. 
<img width="1187" alt="screen shot 2019-02-07 at 3 56 02 pm" src="https://user-images.githubusercontent.com/30784850/52450675-f0ae8e80-2af0-11e9-8866-93a0b7a833b8.png">

**Comment by andrrizzi** [comment] 2019-02-08 08:03
Hi, @jmaat. Yes, it should. Both the stable version in `master` and the development version in the `topology` branch. Let us know if it doesn't as it is likely a bug.

**Comment by jchodera** [comment] 2019-02-08 14:19
I'm not sure I understand how SMIRNOFF trefoil impropers can possibly go past +- 90 degrees, since one of the atoms is already an infinite distance away from the others at that point. How can your function above even approach those limits?

**Comment by j-wags** [comment] 2019-02-08 15:25
Reflecting what Andrea said, we _should_ be able to handle that. I'll be up
in Irvine today and we can try it out.

I'm also thinking about what John said. I think I see what he means, but
I'd like to go over the math for calculating that angle, and figure out
what its range can be if you have time (I'm also happy to do impropers 101
as self study if you're busy today)

**Comment by davidlmobley** [comment] 2019-02-15 21:41
@jchodera I think this was intended as an illustration of the type of double-well behavior we might want to support via a function like that, but it hasn't been scaled to vary over the appropriate range of angles.

**Comment by davidlmobley** [comment] 2019-02-15 21:42
@jmaat I think this is resolved now? If so, can you close the issue?

**Closed** 2019-02-15 21:45 UTC
