### ISSUE TITLE
A

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#636] opened 2020-07-04 02:25 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. A minimal reproducing set of python commands is ideal.

If the problem involves a specific molecule or file, please upload that as well.

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

**Comment by mattwthompson** [comment] 2020-07-06 15:26
Looks like a typo duplicate of #637

**Closed by mattwthompson** 2020-07-06 15:26 UTC
