### ISSUE TITLE
Topology.from_openmm/from_mdtraj don't autoconstruct unique_molecules — docstring wrong?

### ISSUE THREAD

**Issue by corinwagen** [openforcefield/openforcefield#773] opened 2020-11-24 19:59 UTC
**Describe the bug**
[Documentation for openforcefield.topology.Topology](https://open-forcefield-toolkit.readthedocs.io/en/latest/api/generated/openforcefield.topology.Topology.html#openforcefield.topology.Topology.from_mdtraj) states that ``unique_molecules`` can be omitted and the list will be auto-constructed, if possible, from ``mdtraj_topology``.

I spent a while trying to get this to work before looking at the source code and realizing that this feature doesn't seem to be present ([ref](https://open-forcefield-toolkit.readthedocs.io/en/latest/_modules/openforcefield/topology/topology.html#Topology.from_mdtraj)). If I'm wrong, please disregard and close this issue. If I'm right, it would be nice if the docstring were changed to reflect this and not lead unwary sojourners astray with false hope.

**Comment by mattwthompson** [comment] 2020-11-24 20:56
Thanks for the report - I think you're right, as I can reproduce something similar (below). The intended usage of those function is to have a list of `Molecule` objects that specify the molecular connectivity, etc. in a more trusted way that comes through with i.e. a PDB file. It's not clear from the docstring what else is necessary for the "attempt to construct the list of unique Molecules" besides bond orders.

From the git blame, it looks like that docstring is a few years old and the function goes through OpenMM, so something may have gotten lost in those conversions. We'll update the function and/or docstring and make this error more helpful. Thanks!

```
In [1]: import mdtraj as md

In [2]: from openforcefield.topology import Topology

In [3]: trj = md.load("openforcefield/data/systems/test_systems/1_cyclohexane_1_ethanol.pdb")

In [4]: for b in trj.top.bonds:
   ...:     b.order = 1  # Overwrite None values to 1, since PDB files don't come with bond orders
   ...:

In [5]: for b in trj.top.bonds:
   ...:     assert b.order is not None  # Check to make sure all bonds have assigned orders
   ...:

In [6]: top = Topology.from_mdtraj(trj.top)  # This chokes on not having unique_molecules
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-5483eed17073> in <module>
----> 1 top = Topology.from_mdtraj(trj.top)

~/software/openforcefield/openforcefield/topology/topology.py in from_mdtraj(mdtraj_topology, unique_molecules)
   2197         """
   2198         return Topology.from_openmm(
-> 2199             mdtraj_topology.to_openmm(), unique_molecules=unique_molecules
   2200         )
   2201

~/software/openforcefield/openforcefield/topology/topology.py in from_openmm(cls, openmm_topology, unique_molecules)
   1931         topology = cls()
   1932         graph_to_unq_mol = {}
-> 1933         for unq_mol in unique_molecules:
   1934             unq_mol_graph = unq_mol.to_networkx()
   1935             for existing_graph in graph_to_unq_mol.keys():

TypeError: 'NoneType' object is not iterable

In [7]: from openforcefield.topology import Molecule

In [9]: top = Topology.from_mdtraj(trj.top, unique_molecules=[Molecule.from_iupac("cyclohexane"), Molecule.from_iupac(
   ...: "ethanol")])

In [10]: top.n_topology_bonds
Out[10]: 26
```

**Comment by mattwthompson** [comment] 2020-11-30 23:47
@corinwagen thanks again for the report - this is now fixed in the `master` branch and will produce a more informative error message in the upcoming 0.8.1 release (or with a [development](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#setting-up-a-development-environment) install). Outside of that, as you've found, those functions do need `unique_molecules` to be populated with `Molecule` objects.

**Closed** 2020-11-30 23:47 UTC
Labels: bug, documentation, effort:medium
