### ISSUE TITLE
Fix label_molecule.py on topology branch

### ISSUE THREAD

**Issue by proteneer** [openforcefield/openforcefield#187] opened 2019-02-20 18:48 UTC
Some functions have been moved around
``` python
from openforcefield.utils import *
from openforcefield.utils.structure import get_molecule_parameterIDs
from openforcefield.typing.engines.smirnoff import ForceField

from oechem import OEMol, OEParseSmiles, OEAddExplicitHydrogens
```

**Comment by jchodera** [comment] 2019-02-20 19:36
@proteneer : Can you clarify this issue? What exactly is the problem you're reporting here?

**Comment by proteneer** [comment] 2019-02-20 22:15
The current topology branch shows this:

https://github.com/openforcefield/openforcefield/blob/topology/examples/label_molecule/label_molecule.py

Which is *completely* broken.

**Comment by davidlmobley** [comment] 2019-02-20 23:55
I think the issue is just that the examples haven't been updated yet. Or am I missing something?

**Comment by proteneer** [comment] 2019-02-21 00:17
That's pretty much it.

**Comment by j-wags** [comment] 2019-03-11 19:49
We've started taking steps towards a fix in 7de10a3. We'll start on a complete fix after #173 is merged because it makes such significant changes to how parameters are handled.

**Comment by j-wags** [comment] 2019-04-04 19:26
#225 closes this

**Closed by j-wags** 2019-04-04 19:26 UTC
