### ISSUE TITLE
Rigid body MD

### ISSUE THREAD

**Issue by matteo-ambrosetti** [openforcefield/openforcefield#553] opened 2020-03-29 09:16 UTC
I was wondering if it is possible to extend the all-bonds constraint 

`<Constraint smirks="[*:1]-[*:2]" id="c1"></Constraint>`

to angles and dihedral angles. 
Maybe constraining the distance between non-bonded atoms to their equilibrium value.
Is it something doable?

Thanks,

  Matteo

**Comment by j-wags** [comment] 2020-03-31 00:27
Hi @matteo-ambrosetti,

I just tried a few things, and it doesn't look like we can support this easily. It's possible to add arbitrary distance constraints, but to set them in an OpenMM system, we need to provide the distance for each. Constraining bonds is easy, since we already know their equilibrium lengths. However angles would be tricky, and dihedrals don't have a single minimum. Also, the OpenFF toolkit doesn't (currently) consider geometry during parametrization, so setting constraints based on that would be difficult within our architecture.

If I'm not mistaken, constraining all dihedrals is the same as doing rigid body MD. In case you're looking to do that, I dug up a code snippet I put together using [OpenMM's `rigid.py`](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/rigid.py) accessory script. 

Please let me know if you have further questions, or if we can close this issue.

```
from openforcefield.utils import get_data_file_path
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField
from simtk import openmm, unit
import numpy as np
molecule = Molecule.from_file(get_data_file_path('molecules/ethanol.sdf'))
positions = molecule.conformers[0]
positions2 = molecule.conformers[0] + 5.*np.ones(positions.shape)*unit.angstrom
positions = np.concatenate([positions, positions2], axis=0) * unit.angstrom
print(positions.shape)
#positions.extend(molecule.conformers[0]+5.*unit.angstrom)
off_top = Topology.from_molecules([molecule, molecule])
ff = ForceField('openff_unconstrained-1.0.0.offxml')
system = ff.create_openmm_system(off_top)
import rigid
bodies = []
for top_mol in off_top.topology_molecules:
    bodies.append([at.topology_atom_index for at in top_mol.atoms])
rigid.createRigidBodies(system, positions, bodies)

# Propagate the System with Langevin dynamics.
time_step = 2*unit.femtoseconds  # simulation timestep
temperature = 300*unit.kelvin  # simulation temperature
friction = 1/unit.picosecond  # collision rate
integrator = openmm.LangevinIntegrator(temperature, friction, time_step)

# Length of the simulation.
num_steps = 1000  # number of integration steps to run

# Logging options.
trj_freq = 1  # number of steps per written trajectory frame
data_freq = 1  # number of steps per written simulation statistics

# Set up an OpenMM simulation.
simulation = openmm.app.Simulation(off_top.to_openmm(), system, integrator)

# Set the initial positions.
simulation.context.setPositions(positions)

# Randomize the velocities from a Boltzmann distribution at a given temperature.
simulation.context.setVelocitiesToTemperature(temperature)

# Configure the information in the output files.
pdb_reporter = openmm.app.PDBReporter('trajectory.pdb', trj_freq)
state_data_reporter = openmm.app.StateDataReporter('data.csv', data_freq, step=True,
                                                   potentialEnergy=True, temperature=True,
                                                   density=True)
simulation.reporters.append(pdb_reporter)
simulation.reporters.append(state_data_reporter)

import time

print("Starting simulation")
start = time.process_time()

# Run the simulation
simulation.step(num_steps)

end = time.process_time()
print("Elapsed time %.2f seconds" % (end-start))
print("Done!")

**Comment by matteo-ambrosetti** [comment] 2020-03-31 13:59
Thank you @j-wags,
it works perfectly for a low-density system, but I am still experiencing some problem with real systems (e.g. running rigid MD of a box with more than 100 acetonitrile molecules randomly oriented results in error messages). I guess this is probably due to the fact that keeping each molecule rigid leads to a large increment of the system's energy. 
Up to now the only solution I found to this problem was to reduce both the time step and perform an npt equilibration increasing the frequency of barostat to attempt volume changes. I am still not sure about the capability of the system to reach the target density.
If you don't have anything to add I think we can close this issue.
Thanks again for your help!

**Comment by j-wags** [comment] 2020-03-31 15:35
Interesting! I have little experience with this sort of thing, but my experience has been that I have run minimization (`simulation.minimizeEnergy()`) before I attempt to do simulations of packed boxes. 

Also, if you're looking at physical property calculations, you might check out the [openff-evaluator package](https://github.com/openforcefield/openff-evaluator). That's what we're using to reproduce physical properties (though, it doesn't provide an option for rigid bodies).

**Closed by j-wags** 2020-03-31 15:35 UTC
